Fix WORKDIR and COPY commands in Dockerfile
Update:

Fixed the WORKDIR and COPY commands in the Dockerfile.

Previously, due to a path mismatch, the application was unable to locate the required node_modules, resulting in runtime failures.

This issue has now been resolved. The earlier error observed during runtime was related to missing dependencies caused by the incorrect path configuration.

node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module '/opt/app/node_modules/@strapi/strapi/bin/strapi.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}