Update heroku.md
Using git push heroku main produces this error:

 error: src refspec master does not match any.
error: failed to push some refs to 'git@heroku.com
So this solves the issues and pushes to heroku... and give some Clarity config file for production